export const t = {
  app: {
    name: 'Jiraiya',
    paletteHint: '⌘K busca',
    updateAvailable: (version: string) => `v${version} disponível`
  },
  nav: {
    dashboard: 'Dashboard',
    board: 'Quadro',
    ask: 'Perguntar',
    filters: 'Filtros',
    create: 'Criar task',
    split: 'Dividir task',
    timeline: 'Timeline',
    mentions: 'Menções',
    summaries: 'Resumos',
    team: 'Time',
    alerts: 'Alertas',
    settings: 'Configurações'
  },
  sync: {
    syncNow: 'Sincronizar',
    syncing: 'Sincronizando…',
    lastSync: (ago: string) => `Sincronizado ${ago}`,
    never: 'Nunca sincronizado',
    phases: {
      issues: 'Buscando issues…',
      activities: 'Processando atividades…',
      sprints: 'Atualizando sprints…'
    } as Record<string, string>,
    error: 'Falha na sincronização'
  },
  onboarding: {
    title: 'Conectar ao Jira',
    subtitle: 'Conecte sua conta do Jira Cloud para começar.',
    siteUrl: 'URL do site',
    siteUrlPlaceholder: 'suaempresa.atlassian.net',
    email: 'E-mail',
    apiToken: 'API token',
    tokenHelp: 'Crie um token em',
    tokenLinkLabel: 'id.atlassian.com/manage-profile/security/api-tokens',
    testAndConnect: 'Testar e conectar',
    connecting: 'Conectando…',
    connected: (name: string) => `Conectado como ${name}`,
    selectProjects: 'Selecione os projetos',
    selectProjectsSubtitle: 'Escolha os projetos que o Jiraiya vai acompanhar.',
    loadingProjects: 'Carregando projetos…',
    continue: 'Continuar',
    back: 'Voltar',
    initialSync: 'Sincronização inicial',
    initialSyncSubtitle: 'Baixando issues e atividades recentes. Isso pode levar alguns minutos.',
    start: 'Começar a usar',
    syncDone: 'Tudo pronto!',
    noProjects: 'Nenhum projeto encontrado.',
    selectAtLeastOne: 'Selecione pelo menos um projeto.'
  },
  common: {
    save: 'Salvar',
    cancel: 'Cancelar',
    copy: 'Copiar',
    copied: 'Copiado!',
    export: 'Exportar .md',
    delete: 'Excluir',
    dismiss: 'Dispensar',
    loading: 'Carregando…',
    empty: 'Nada por aqui.',
    error: 'Algo deu errado',
    retry: 'Tentar novamente'
  },
  authInvalid: 'Credenciais do Jira expiraram — reconecte em Configurações.',
  create: {
    title: 'Criar task',
    whereTitle: 'Onde',
    project: 'Projeto',
    issueType: 'Tipo',
    loadingIssueTypes: 'Carregando tipos…',
    noIssueTypes: 'Não é possível criar issues neste projeto por aqui.',
    aiTitle: 'Gerar com IA',
    ideaLabel: 'Descreva a ideia da task',
    ideaPlaceholder:
      'Ex.: contexto (onde/por que isso importa), o que precisa ser feito e o comportamento esperado ao final.',
    generate: 'Gerar título e descrição',
    generating: 'Gerando…',
    claudeUnavailableHint: 'Instale o Claude Code para gerar rascunhos',
    cardTitle: 'Card',
    summary: 'Título',
    description: 'Descrição',
    descriptionHint:
      'Use ###, **negrito**, - listas e - [ ] checklists — o Jiraiya converte para o formato do Jira.',
    assignToMe: 'Atribuir a mim',
    addToActiveSprint: (sprintName: string) => `Adicionar à sprint ativa — ${sprintName}`,
    storyPoints: 'Story points',
    storyPointsHint: 'Opcional',
    submit: 'Criar no Jira',
    submitting: 'Criando…',
    createdTitle: (key: string) => `Task ${key} criada`,
    createdHint: 'Ela aparece no app após a sincronização (alguns segundos).',
    openInJira: 'Abrir no Jira',
    createAnother: 'Criar outra'
  },
  split: {
    title: 'Dividir task',
    whichCardTitle: 'Qual card dividir?',
    selectLabel: 'Meus cards abertos',
    selectPlaceholder: 'Selecione um card',
    orManualKey: 'ou informe a key',
    manualKeyPlaceholder: 'Ex.: BT-123',
    search: 'Buscar',
    searching: 'Buscando…',
    notFound: 'Card não encontrado localmente — verifique a key ou sincronize.',
    noDescription: 'Este card não tem descrição — a análise será baseada só no título.',
    analyze: 'Analisar com Claude',
    analyzing: 'Analisando… pode levar alguns minutos',
    claudeUnavailableHint: 'Instale o Claude Code para analisar cards',
    rationaleTitle: 'Critério da divisão',
    itemsTitle: 'Itens da divisão',
    itemTitleLabel: 'Título',
    itemDescriptionLabel: 'Descrição',
    removeItem: 'Remover item',
    addItem: '+ Adicionar item',
    feedbackLabel: 'Feedback para o Claude',
    feedbackPlaceholder: 'Ex.: junte os itens 2 e 3; adicione um item de testes e2e',
    refine: 'Refinar com Claude',
    refining: 'Analisando… pode levar alguns minutos',
    structureTitle: 'Estrutura',
    modeSubtask: 'Subtarefas do card original',
    modeSibling: 'Cards irmãos (mesmo projeto)',
    noSubtaskType: 'Este projeto não tem tipo de subtarefa',
    issueType: 'Tipo',
    assignToMe: 'Atribuir a mim',
    submit: (n: number) => `Criar ${n} card${n === 1 ? '' : 's'} no Jira`,
    submitting: 'Criando…',
    createdTitle: (n: number, parentKey: string) =>
      `${n} card${n === 1 ? '' : 's'} criado${n === 1 ? '' : 's'} a partir de ${parentKey}`,
    commentFailedHint: 'Os cards foram criados, mas o comentário no card original falhou.',
    openParentInJira: 'Ver card original',
    splitAnother: 'Dividir outro'
  },
  ask: {
    title: 'Perguntar ao Jiraiya',
    hint: 'Responde com base nos seus dados locais (janela de backfill)',
    placeholder: 'Pergunte algo sobre seus cards, sprint ou time…',
    send: 'Enviar',
    thinking: 'Pensando… (pode levar alguns minutos)',
    clearConversation: 'Limpar conversa',
    claudeUnavailableHint: 'Instale o Claude Code para perguntar ao Jiraiya',
    suggestions: [
      'O que travou a sprint essa semana?',
      'Resume o feedback que recebi nos meus cards',
      'Quais cards estão parados e por quê?'
    ] as string[]
  },
  filters: {
    title: 'Filtros',
    savedTitle: 'Salvos',
    newFilter: '+ Novo filtro',
    noSavedFilters: 'Nenhum filtro salvo ainda.',
    nameLabel: 'Nome',
    namePlaceholder: 'Ex.: Bugs críticos abertos',
    jqlLabel: 'JQL',
    jqlPlaceholder: 'Ex.: project = BT AND status != Done ORDER BY priority DESC',
    jqlExamplesHint:
      'Exemplos: assignee = currentUser() AND resolution = Unresolved · project = BT AND priority = Highest ORDER BY updated DESC',
    run: 'Executar',
    running: 'Executando…',
    save: 'Salvar',
    saving: 'Salvando…',
    editTitle: 'Editar filtro',
    edit: 'Editar',
    delete: 'Excluir',
    deleteConfirm: 'Excluir?',
    yes: 'Sim',
    no: 'Não',
    resultsCount: (n: number) => `${n} resultado${n === 1 ? '' : 's'}`,
    truncatedHint: 'Mostrando os primeiros 50.',
    empty: 'Nenhum resultado.',
    runToSeeResults: 'Execute o JQL para ver os resultados.'
  },
  board: {
    title: 'Quadro',
    boardLabel: 'Board',
    boardPlaceholder: 'Selecione um board',
    sprintLabel: 'Sprint',
    sprintPlaceholder: 'Selecione uma sprint',
    sprintFallbackName: (jiraId: number) => `Sprint ${jiraId}`,
    activeSuffix: ' (ativa)',
    closedSuffix: ' (encerrada)',
    readOnlyBadge: 'Sprint encerrada — somente leitura',
    noActiveSprint: 'Sem sprint ativa',
    outOfBoard: 'Fora do quadro',
    noAssignee: 'Sem responsável',
    all: 'Todos',
    you: 'você',
    fallbackBanner: 'Colunas aproximadas (configuração do board indisponível)',
    empty: 'Nenhum card nesta coluna.'
  },
  detail: {
    openInJira: 'Abrir no Jira',
    close: 'Fechar',
    notSynced: 'Este card ainda não foi sincronizado localmente.',
    storyPoints: (n: number) => `${n} pts`,
    description: 'Descrição',
    showAll: 'mostrar tudo',
    timeInStatus: 'Tempo por status',
    cardTimeline: 'Timeline do card',
    noActivity: 'Nenhuma atividade registrada.',
    commentsTitle: 'Comentários',
    noComments: 'Nenhum comentário ainda.',
    commentsOfflineHint: 'Sem conexão com o Jira — mostrando versão local em texto simples.',
    commentTitle: 'Comentar',
    commentPlaceholder: 'Escreva um comentário para postar no Jira…',
    commentSubmit: 'Comentar no Jira',
    commentSending: 'Enviando…',
    aiStructure: 'Estruturar com IA',
    aiNotesPlaceholder: 'Notas rápidas — o Claude estrutura em um comentário.',
    aiGenerate: 'Gerar comentário',
    aiGenerating: 'Gerando…',
    claudeUnavailableHint: 'Instale o Claude Code para estruturar comentários com IA',
    editTitle: 'Editar',
    save: 'Salvar',
    saving: 'Salvando…',
    nothingChanged: 'Nada para salvar',
    storyPointsLabel: 'Story points',
    priorityLabel: 'Prioridade',
    severityPlaceholder: '—',
    originalEstimateLabel: 'Estimativa original',
    originalEstimatePlaceholder: '2d 4h',
    timeSpentRegistered: (value: string | null) => `Registrado: ${value ?? '—'}`,
    timeSpentEstimated: (value: string) => `estimado: ${value}`,
    timeSpentPlaceholder: '1h 30m',
    timeSpentHint: 'Formato: 1w 2d 3h 30m',
    logWork: 'Registrar',
    logging: 'Registrando…',
    backLabel: 'Voltar',
    moveTo: 'Mover para…',
    moving: 'Movendo…',
    moved: 'Movido!',
    relatedTitle: 'Relacionados',
    parentLabel: 'Pai',
    subtasksTitle: (n: number) => `Subtarefas (${n})`,
    linksTitle: 'Vinculados',
    linksOffline: 'Sem conexão com o Jira para listar vínculos.',
    assigneeLabel: 'Responsável',
    unassigned: 'Sem responsável',
    meSuffix: ' (eu)',
    attachmentsTitle: 'Anexos',
    addSubtask: '+ Subtarefa',
    subtaskTitlePlaceholder: 'Título da subtarefa…',
    subtaskCreate: 'Criar',
    subtaskCreating: 'Criando…',
    editComment: 'Editar comentário',
    deleteComment: 'Excluir comentário',
    deleteConfirm: 'Excluir?',
    yes: 'Sim',
    no: 'Não',
    commentEditHint: 'salvar substitui a formatação original pela do editor (###, **, listas)'
  },
  palette: {
    placeholder: 'Buscar card por key, título ou texto…',
    minChars: 'Digite ao menos 2 caracteres para buscar.',
    noResults: 'Nada encontrado.',
    hintOpen: '↵ abrir · ⌘↵ abrir no Jira'
  }
}
